/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package telas;

import dao.ConexaoBanco;
import dao.EventoDao;
import dao.InscricaoDao;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Evento;
import modelo.Sessao;
import modelo.Usuario;

/**
 *
 * @author João
 */
public class TelaEventos extends javax.swing.JInternalFrame {

    /**
     * Creates new form Eventos
     */
    public TelaEventos() {
        initComponents();
        CarregarEventos();
    }
    private void CarregarEventos(){
          try{
            // Instancia o dao e chama o método para obter os dados do cardápio
            ConexaoBanco conexx = new ConexaoBanco();// chama a conexao do banco de dados
           EventoDao eventos = new EventoDao (conexx.c); // conexao com a classe que interage com o banco
           List<Evento> EventoLista = eventos.CarregarEventos(); // chama a o metodo de carregar os dados das bebidas

            // obtem o modelo da tabela e limpa as linhas que estao existentes
            DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel(); // O jTable pega os dados cadastrados(nesse caso o cardapio)
            modelo.setRowCount(0); // Limpa a tabela antes de adicionar novos dados

            // Adiciona os dados recuperados na tabela
            for (Evento be : EventoLista) {
                Object[] row = {
                    be.getId(),
                    be.getNome(),
                    be.getDescricao(),
                    be.getDt_inicio(),
                    be.getDt_fim(),
                    be.getEndereco()
                };
                modelo.addRow(row);
            }

          } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao carregar dados dos eventos: " + e.getMessage());
            e.printStackTrace();
         }
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome", "Descrição", "Início", "Fim", "Local"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Inscrever-se");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Voltar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 86, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(59, 59, 59))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))))
        );

<<<<<<< HEAD
        setBounds(0, 0, 406, 321);
=======
        getAccessibleContext().setAccessibleName("Minhas Incrições");

        pack();
>>>>>>> 1c475c833866f21b0d434baf1340d4f83b95a634
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
           
        int selectedrow = jTable1.getSelectedRow();
        
        if(selectedrow != -1){
            int id_even = (int)jTable1.getValueAt(selectedrow, 0);
            Usuario usuario = Sessao.getInstancia().getUsuarioLogado();
            ConexaoBanco conexao = new ConexaoBanco(); 
            
            InscricaoDao dao = new InscricaoDao (conexao.c);
            
            String inscrito = dao.AddInscricao(id_even, usuario.getId());
            
            if(inscrito.equals("Inscrito com sucesso")){
                //  principalmente ele remove a linha correspondente na tabela
               JOptionPane.showMessageDialog(null, "Inscrição realizada"); 
            }else{
               JOptionPane.showMessageDialog(null, "Erro ao realizar sua Inscrição");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Selecione um evento");
        }
       }catch(Exception e){
           JOptionPane.showMessageDialog(null, "Ocorreu um erro se inscrever no evento " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
       }
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
